version: "3.9"

services:
  redis:
    image: redis

  app:
    build:
      context: ./
    ports:
      - "3030:3030"
    command:
      [
        "python3",
        "./src/manage.py",
        "runserver",
        "0.0.0.0:3030"
      ]

  worker:
    build:
      context: ./
    volumes:
      - ./src/downloads:/app/src/downloads
    command:
      [
        "celery",
        "--workdir=./src",
        "-A",
        "catdownloader",
        "worker"
      ]
