version: "3.9"

services:
  redis:
    image: redis
    restart: always

  app:
    restart: always
    build:
      context: ./
    ports:
      - "3030:3030"
    command:
      [
        "python3",
        "./src/manage.py",
        "runserver",
        "0.0.0.0:3030"
      ]
